# Generated by Django 3.0 on 2020-05-18 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200518_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='post_author',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
