# Generated by Django 3.0 on 2020-05-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_entry_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='post_author',
            field=models.CharField(default='', max_length=25),
        ),
    ]
